version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  mongo:
    image: 'mongo'
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - SECRET_KEY=v2FYSR7rWMqwuDUB
      - DB_URI=mongodb://mongo:27017
      - DB_NAME=pizzas
      - PORT=5000
  client:
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app